# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DNe8mSoTH0rIYljRZKW6aQe8CPXERvwr
"""

students = [
    {"nombre": "José", "notas": [85, 90, 78, -10]},
    {"nombre": "Carlos", "notas": [88, 72, 94, 102]},
    {"nombre": "María", "notas": [95, 85, 87, "A++"]},
    {"nombre": "Valentina", "notas": [95, 85, 87, "A++"]},
    {"nombre": "Guillermina", "notas": ["A", "B", "C", "D"]},
    {"nombre": "Chiara", "notas": [-95, -85, -87, -17]},
]

for student in students:
  nombre = student["nombre"]
  notas = student ["notas"]
  notas_validas = []
  notas_invalidas = []
  for nota in notas:
        tipo_de_nota = type(nota)
        if (tipo_de_nota == int or tipo_de_nota == float) and 0 <= nota <= 100:
            notas_validas.append(nota)
        else:
            notas_invalidas.append(nota)
  if notas_validas:
        suma = sum(notas_validas)
        promedio = suma / len(notas_validas)
        print(f"El promedio de las notas válidas de {nombre} es: {promedio}")
  else:
        print(f"{nombre} no tiene notas válidas.")
  if notas_invalidas:
        print(f"Las notas inválidas de {nombre} son: {notas_invalidas}")